artifact_root: artifact

data_ingestion:
  root_dir: artifact/data_ingestion
  source_url: https://drive.google.com/file/d/14qbcWr-mgHMvbYgJmIN9HUBJPGeYaain/view?usp=sharing
  local_data_file: artifact/data_ingestion/data.zip
  unzip_dir: artifact/data_ingestion

base_model:
  root_dir: artifact/base_model
  base_model_dir: artifact/base_model/base_model.h5
  updated_base_model_dir: artifact/base_model/updated_base_model.h5